directory "build"

task :default => [:parse, :lint] do
  sh "vagrant provision"
end


task :rebuild do
  sh "bundle exec vagrant destroy"
  sh "bundle exec vagrant up"
  sleep 60 # wait for jetty to start
  sh "open http://192.168.0.3/app/"
end

desc "fetch graphs from the machine"
task :graph => :default do
  sh  "vagrant ssh_config > build/ssh_config"
  sh  "scp -F build/ssh_config default:/var/lib/puppet/state/graphs/expanded_relationships.dot build"
  sh "dot -Tsvg -O build/expanded_relationships.dot"
end

desc "lint the puppet code"
task :lint do
  Dir["**/*.pp"].each do |puppet_file|
    sh "bundle exec puppet-lint #{puppet_file}"
  end
end

desc "Parse all puppet files"
task :parse do
  file = File.open("build/parseonly.pp","w+")
  Dir.glob('etc/puppet/**/*.pp').each { |manifest| file <<  "import '#{manifest}'\n" }
  sh "bundle exec puppet parser validate build/parseonly.pp"
end

