Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.host_name  = 'www.corporateapp.com'
  config.vm.network '192.168.0.3'
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    #puppet.manifest_file  = "03_installed_app_on_nginx_and_jetty.pp"
    puppet.manifest_file  = "site.pp"
    puppet.options = "--color false"
  end
end
