Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.forward_port("web", 80, 8080, :auto => true)
  config.vm.forward_port("ssh", 22, 2222, :auto => true)
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "03_installed_app_on_nginx_and_jetty.pp"
    puppet.options = "--graph"
  end
end
